//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13_ProyectoTaxi.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaLog
    {
        public int id { get; set; }
        public Nullable<int> idTarea { get; set; }
        public string op { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    }
}
