//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace M13_ProyectoTaxi.Model.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int id { get; set; }
        public string telefono { get; set; }
        public string nombre { get; set; }
        public string direccion { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<System.DateTime> fechaRecogida { get; set; }
        public Nullable<System.DateTime> fechaCompletada { get; set; }
        public Nullable<int> FK_TaxistaId { get; set; }
        public Nullable<int> FK_ZonaId { get; set; }
    
        public virtual Taxista Taxista { get; set; }
        public virtual Zona Zona { get; set; }
    }
}
